# Generated by Django 3.2.8 on 2022-01-28 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutinfo',
            name='workout_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_workout_info_workoutname', to='workout.workoutinfo'),
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayhistoryuserinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_history_user_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
