# Generated by Django 3.2.8 on 2022-01-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutinfo',
            name='target_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userworkoutinfo',
            name='target_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
