# Generated by Django 3.2.8 on 2022-01-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220128_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworkoutinfo',
            old_name='workout_kg',
            new_name='target_kg',
        ),
    ]
