# Generated by Django 3.2.8 on 2022-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_workout_kg_userworkoutinfo_target_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutinfo',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
