# Generated by Django 3.2.8 on 2022-01-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayhistoryextraworkout',
            old_name='workoutInfo_name',
            new_name='workout_name',
        ),
        migrations.RenameField(
            model_name='dayhistoryworkout',
            old_name='workoutInfo_name',
            new_name='workout_name',
        ),
    ]
