# Generated by Django 3.2.8 on 2022-03-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutinfo',
            name='body_part',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
