# Generated by Django 3.2.8 on 2021-11-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20211011_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhistory',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayhistory',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
