# Generated by Django 3.2.8 on 2022-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20220107_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhistoryworkout',
            name='target_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayhistoryworkout',
            name='target_set',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
